services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - MODEL_DIR=/app/ai_model
      - RUST_LOG=info
    restart: unless-stopped