global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Сам Prometheus
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: traefik
    metrics_path: /metrics
    static_configs:
      - targets: ['traefik:8080']

  # - job_name: backend
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets: ['backend:8080']